# basic
title: Daily
subtitle: Minimalism, simplicity and refined details
favicon: http://oj7lzlt0w.bkt.clouddn.com/shouDevfavicon.ico
language: zh-CN

logo: http://oj7lzlt0w.bkt.clouddn.com/shouDevlogo2.svg

# disqus
#disqus_shortname: drakeleung

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# nav #
nav:
  首页: .
  所有文章: archives
  关于: about
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/shouDeveloper
  # weibo: http://weibo.com/10010800
  # mail: mailto:gallenhu@foxmail.com
  # twitter: https://twitter.com/GallenHu

# widget
#   title: 标题
#   content: 内容
widget:
  title: 关于我们
  content: <ul><li></li></ul>

footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> with Theme <a href="https://github.com/GallenHu/hexo-theme-Daily" target="_blank">Daily</a> diy by <a href="https://github.com/garychangcn">@GaryChangCN</a>
